# Generated by Django 6.0.5 on 2026-08-14 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_by', models.CharField(choices=[('owner', 'Owner'), ('agent', 'Agent'), ('builder', 'Builder')], default='owner', max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], db_index=True, max_length=20)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('plot', 'Plot/Land'), ('office', 'Office Space'), ('shop', 'Shop/Retail'), ('warehouse', 'Warehouse')], max_length=50)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], db_index=True, max_length=10)),
                ('bhk', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('area_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_available', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app72acres.property')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('agent', 'Agent'), ('builder', 'Builder')], db_index=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
