# Generated by Django 6.0.5 on 2026-09-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app72acres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
