# Generated by Django 6.1 on 2026-09-21 09:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lister_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('flat', 'Flat'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('studio_apartment', 'Studio Apartment'), ('farmhouse', 'Farmhouse'), ('plot', 'Plot'), ('office', 'Office'), ('shop', 'Shop'), ('land', 'Land')], max_length=20)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease')], max_length=10)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit pincode.')])),
                ('carpet_area', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('area_unit', models.CharField(choices=[('sqft', 'Sq. Ft.'), ('acre', 'Acre')], default='sqft', max_length=10)),
                ('bhk', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 BHK'), (2, '2 BHK'), (3, '3 BHK'), (4, '4 BHK'), (5, '5 BHK')], null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Bathroom'), (2, '2 Bathrooms')], null=True)),
                ('balconies', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'No Balcony'), (1, '1 Balcony'), (2, '2 Balconies'), (3, '3 Balconies'), (4, '4 Balconies')], null=True)),
                ('floor', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Ground Floor'), (1, '1st Floor'), (2, '2nd Floor'), (3, '3rd Floor'), (4, '4th Floor'), (5, '5th Floor'), (6, '6th Floor'), (7, '7th Floor'), (8, '8th Floor'), (9, '9th Floor'), (10, '10+ Floor')], null=True)),
                ('total_floors', models.CharField(blank=True, choices=[('1-5', '1–5 Floors'), ('6-10', '6–10 Floors'), ('11-20', '11–20 Floors'), ('21-30', '21–30 Floors'), ('30+', '30+ Floors')], max_length=10)),
                ('furnishing', models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished')], max_length=20)),
                ('parking', models.CharField(blank=True, choices=[('none', 'No Parking'), ('open', 'Open Parking'), ('covered', 'Covered Parking'), ('basement', 'Basement Parking'), ('mechanical', 'Mechanical Parking')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('construction_status', models.CharField(choices=[('ready_to_move', 'Ready to Move'), ('under_construction', 'Under Construction'), ('new_launch', 'New Launch'), ('upcoming', 'Upcoming'), ('resale', 'Resale')], max_length=20)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('rera_registered', models.BooleanField(default=False)),
                ('rera_number', models.CharField(blank=True, max_length=50)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('image_1', models.ImageField(upload_to='properties/')),
                ('image_2', models.ImageField(blank=True, upload_to='properties/')),
                ('image_3', models.ImageField(blank=True, upload_to='properties/')),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
